# Generated by Django 3.1.4 on 2021-10-22 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211022_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 18, 16, 14, 99346, tzinfo=utc)),
        ),
    ]
