# Generated by Django 3.1.4 on 2021-10-22 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211022_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 18, 28, 13, 855483, tzinfo=utc)),
        ),
    ]
