# Generated by Django 3.1.4 on 2021-10-23 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211023_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 11, 17, 19, 441850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.FileField(upload_to='media'),
        ),
    ]
